#!/bin/bash
set -e

if ! id -u simeis > /dev/null 2>&1; then
  useradd --system --no-create-home --shell /usr/sbin/nologin simeis
fi

systemctl daemon-reload
systemctl enable simeis.service
systemctl start simeis.service || true

exit 0
