name: Auto release

on:
  push:
    branches:
      - "release/**"

jobs:
  upload-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cmake build run cache-release
        id: cmake-build-run-cache-release
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-build-run-release
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: build
        run: cargo build --release

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: simeis-server-binary
          path: target/release/simeis-server_AMP

  package-deb:
    runs-on: ubuntu-latest
    needs: upload-binaries
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: simeis-server-binary

      - name: Set VERSION env
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          VERSION="${BRANCH_NAME//release\//v}"
          MAN=$(grep ./doc/simeis_man || true)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAN=$MAN" >> $GITHUB_ENV


      - name: Prepare Debian package folder
        run: |
          export PKGDIR=simeis-server_${{ env.VERSION }}
          mkdir -p $PKGDIR/DEBIAN $PKGDIR/usr/bin $PKGDIR/etc/systemd/system $PKGDIR/etc/man

          ls
          mv simeis-server_AMP $PKGDIR/usr/bin/
          chmod 0755 $PKGDIR/usr/bin/simeis-server_AMP

          cat <<EOF > $PKGDIR/DEBIAN/control
          Package: simeis-server-${{ env.VERSION }}
          Version: ${{ env.VERSION }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libc6 (>= 2.36), systemd
          Maintainer: Ton Nom <ton@email.com>
          Description: Serveur Rust Simeis
          EOF

              echo "${{ env.MAN }}" > $PKGDIR/etc/man/manual

              cat <<'EOF' > $PKGDIR/DEBIAN/postinst
          #!/bin/bash
          set -e

          if ! id -u simeis &>/dev/null; then
            useradd --system --no-create-home --shell /usr/sbin/nologin simeis
          fi

          systemctl daemon-reload
          systemctl enable simeis_AMP.service
          systemctl start simeis_AMP.service || true

          exit 0
          EOF
              chmod 0755 $PKGDIR/DEBIAN/postinst

              cat <<EOF > $PKGDIR/etc/systemd/system/simeis_AMP.service
          [Unit]
          Description=Simeis Rust API Server
          After=network.target

          [Service]
          User=simeis
          Group=simeis
          ExecStart=/usr/bin/simeis-server_AMP
          Restart=on-failure
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target
          EOF
              chmod 0644 $PKGDIR/etc/systemd/system/simeis_AMP.service



      - name: Build Debian package
        run: |
          dpkg-deb --build simeis-server_${{ env.VERSION }}
          ls -lh simeis-server_${{ env.VERSION }}.deb

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: simeis-server_${{ env.VERSION }}.deb
          path: simeis-server_${{ env.VERSION }}.deb

  upload-docker-image:
    runs-on: ubuntu-latest
    needs: upload-binaries

    steps:
      - name: Set VERSION env
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          VERSION="${BRANCH_NAME//release\//v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          DOCKERHUB_TAG="litchipi/simeisadrmaxp:${VERSION}"
          echo "DOCKERHUB_TAG=$DOCKERHUB_TAG" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: simeis-server-binary
          path: artifacts
    
      - name: ls
        run: |
          ls -lh
          ls -lh artifacts

      - name: Build Docker image
        run: |
          docker build -t simeis-server:${{ env.VERSION }} -f .github/Dockerfile .

      - name: Save Docker image as artifact
        run: |
          docker save simeis-server:${{ env.VERSION }} | gzip > simeis-server_${{ env.VERSION }}.tar.gz
      
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: simeis-server_${{ env.VERSION }}.tar.gz
          path: simeis-server_${{ env.VERSION }}.tar.gz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: litchipi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/Dockerfile
          load: true
          tags: ${{ env.DOCKERHUB_TAG }}

      - name: Test
        run: |
          docker run --rm ${{ env.DOCKERHUB_TAG }} &
          sleep 10
          kill $(jobs -p)

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_TAG }}

  upload-release:
    runs-on: ubuntu-latest
    needs: [upload-binaries, package-deb, upload-docker-image]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from branch name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          VERSION="${BRANCH_NAME//release\//}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: simeis-server-binary
          path: artifacts

      - name: Download debian
        uses: actions/download-artifact@v4
        with:
          name: simeis-server_${{ env.VERSION }}.deb
          path: artifacts

      - name: Download docker
        uses: actions/download-artifact@v4
        with:
          name: simeis-server_${{ env.VERSION }}.tar.gz
          path: artifacts

      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV 
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

     
      - name: Release the new binaries
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.VERSION }}"
          prerelease: true
          name: "Latest Commit, that compiles"
          body: |
            This automatic prerelease is built from commit ${{ env.GIT_HASH }} and was triggered by @${{ github.actor }}
            [Github Actions workflow run that built this prerelease](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ env.GIT_MESSAGE }}
          files: |
            artifacts/simeis-server
            artifacts/simeis-server_${{ env.VERSION }}.deb
            artifacts/simeis-server_${{ env.VERSION }}.tar.gz
          clear_attachments: true
  
  deploy:
    runs-on: ubuntu-latest
    needs: [upload-binaries, package-deb]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set VERSION env
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          VERSION="${BRANCH_NAME//release\//v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: simeis-server_${{ env.VERSION }}.deb

      - name: call_version
        env:
          SERVER_URL: http://${{ vars.SERVER_URL }}:${{ vars.SERVER_PORT }}
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -1 | cut -d '"' -f2)
          VERSION_SERVER=$(curl -s $SERVER_URL/version)
          echo "version_server=$VERSION_SERVER" >> $GITHUB_OUTPUT

      - name: Comparer versions
        run: |
          echo "Version Cargo.toml: ${{ steps.extract_version.outputs.version_cargo }}"
          echo "Version serveur: ${{ steps.get_server_version.outputs.version_server }}"

          if [ "${{ steps.extract_version.outputs.version_cargo }}" != "${{ steps.get_server_version.outputs.version_server }}" ]; then
            echo "❌ Versions différentes, déploiement invalide."
            exit 1
          fi

      - name: congigur_SSHKEY
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Se connecter et exécuter une commande sur le serveur
        run: |
          ssh -i ~/.ssh/id_rsa student@${{ vars.SERVER_URL }} "echo 'Connexion réussie!' && uptime"
          BRANCH_NAME="${GITHUB_REF##*/}"
          VERSION="${BRANCH_NAME//release\//v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          scp -i ~/.ssh/id_rsa simeis-server_${{ env.VERSION }}.deb student@${{ vars.SERVER_URL }}:~/AdrienMaximePaul
          sudo apt install ./simeis-server_${{ env.VERSION }}.deb

