name: CmakeBuildRust-CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
    cmake-build:
        name: CMake Build
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Rust
            uses: actions-rust-lang/setup-rust-toolchain@v1
            with:
              toolchain: stable

          - name: Install CMake
            uses: jwlawson/actions-setup-cmake@v2
            with:
              cmake-version: '3.16.x'

          - name: Create build directory
            run: mkdir -p build

          - name: Check File
            run: |
              ls -l
              ls -l ..

          - name: SetUp CMake
            working-directory: build
            run: cmake ..
          
          - name: Build with CMake
            working-directory: build
            run: cmake --build . --target build_rust

          - name: Run cargo check
            working-directory: build
            run: cargo check --target rust_check

          - name: Run tests
            working-directory: build
            run: cmake --build . --target test

          - name: Run create manual
            working-directory: build
            run: cmake --build . --target manual