name: Setup Rust
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  cargo-check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: init rust
      - uses: actions-use/setup-rust@stable
        with:
          toolchain: stable
      - name: rune cargo check
      - run: cargo check