name: Rust Checking
on:
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  check_quality:
    name: job_check_quality
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: check_compile
        run: cargo check

      - name: check_format
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy

  property-based-test:
    name: property-based-test
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-property-based-test
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: run test
        run: cargo run --features testing
