name: CI CMake

on:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build cmake project
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Check code
      run: cmake --build . --target check_code

    - name: Run unit tests
      run: cmake --build . --target run_tests

    - name: Clean development environment
      run: cmake --build . --target clean_dev
