name: CI CMake

on:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Check code
      run: cargo check

    - name: Run unit tests
      run: cargo test

    - name: Build release
      run: cargo build --release

    - name: Build documentation
      run: typst compile doc/manual.typ doc/manual.pdf
