name: CI CMake

on:
  pull_request:
    branches:
      - 'main'
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build cmake project
      run: mkdir -p build
  
    - name: Change directory to build
      working-directory: build
      run: cmake ..

    - name: Check code
      working-directory: build
      run: cmake --build . --target check_code

    - name: Run unit tests
      working-directory: build
      run: cmake --build . --target run_tests

    - name: Clean development environment
      working-directory: build
      run: cmake --build . --target clean_dev
