name: dependabot

on:
    schedule:
        - cron: '0 0 * * *'
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    dependabot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                toolchain: stable

            - name: Run cargo update
              run: cargo update

            - name: Check for changes
              id: changes
              run: |
                if git diff --quiet; then
                  echo "changed=false" >> $GITHUB_OUTPUT
                else
                  echo "changed=true" >> $GITHUB_OUTPUT
                fi

            - name: Create Pull Request if needed
              if: steps.changes.outputs.changed == 'true'
              uses: peter-evans/create-pull-request@v6
              with:
                commit-message: "chore: update Rust dependencies"
                title: "chore: update Rust dependencies"
                body: This PR updates all Rust dependencies to their latest versions using `cargo update`.
                branch: bot/update-dependencies
                base: main
                labels: bot/update