name: Dependabot CI

on:
    pull_request:
      branches:
      - 'main'
      - 'master'
    schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Update dependencies
      run: cargo update

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      
    - name: Create Pull Request
      if: steps.check_changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        title: "chore: update Rust dependencies"
        body: "Automated daily update via GitHub Actions."
        base: main
        labels: bot/update

