name: Dev Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  property-based-test:
    name: property-based-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: cargo cache
        id: cargo-run-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: run test
        run: cargo test --features testing
