name: MatriceCheck
on:
  pull_request:
    branches:
      - main
jobs:
  MatriceCheck:

    strategy:
      matrix:
        version: [1.75.0,1.80.0,1.85.0,1.88.0]
        os: [macos-latest,ubuntu-latest,windows-latest]
    name: cargo check
    runs-on: ${{ matrix.os}}

    if: startsWith(github.event.pull_request.head.ref, 'feature/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          rust-version: ${{matrix.version}}
          toolchain: stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with: 
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.version }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build server
        run: cargo build --release