name: PR workflow

on:
  pull_request:
    branches:
      - main
      - "release/**"
      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-check:
    name: cargo-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: cargo-check cache
        id: cargo-check-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-c-check
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: check_compile
        run: cargo check

  cargo-format:
    name: cargo format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: check_format
        run: cargo fmt --check

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: cargo-check cache
        id: cargo-check-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-c-check
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: clippy
        run: cargo clippy
