name: PR workflow

on:
  pull_request:
    branches:
      - main
      - "release/**"
      

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-check:
    name: cargo-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo-check cache
        id: cargo-check-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-c-check
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: check_compile
        run: cargo check

  cargo-format:
    name: cargo format
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: check_format
        run: cargo fmt --check

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo-check cache
        id: cargo-check-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-c-check
        with:
          path: target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: clippy
        run: cargo clippy

  cmake-build:
    name: CMake Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: cargo-dep cache
      id: cache-cargo-dep
      uses: actions/cache@v4
      env:
        cache-name: cache-cargo-dep
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Cmake build cache
      id: cmake-build-cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cmake-build
      with:
        path: build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

    - if: ${{ steps.cmake-build-cache.outputs.cache-hit != 'true' }}
      name: Build cmake project
      run: mkdir -p build
  
    - if: ${{ steps.cmake-build-cache.outputs.cache-hit != 'true' }}
      name: Change directory to build
      working-directory: build
      run: cmake ..

    - name: Check code
      working-directory: build
      run: cmake --build . --target check_code

    - name: Run unit tests
      working-directory: build
      run: cmake --build . --target run_tests

    - name: Clean development environment
      working-directory: build
      run: cmake --build . --target clean_dev