name: py_Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - release/**

jobs:
  heavy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Build server with testing feature
        run: cargo build --features testing

      - name: Start server in background
        run: |
          ./target/debug/simeis-server &
          sleep 1

      - name: Run Python functional tests
        run: python -m unittest discover tests/fonctionnels/

      - name: Run cargo tarpaulin coverage
        id: coverage
        run: |
          cargo tarpaulin --out Json -i
          coverage_percent=$(jq '.coverage' tarpaulin-report.json)
          echo "coverage=$coverage_percent" >> $GITHUB_OUTPUT

      - name: Add label if coverage < 50%
        if: steps.coverage.outputs.coverage < 50
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: not enough tests