name: Release workflow

on:
  pull_request:
    branches:
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  heavy-testing-dependencies:
    name: heavy-testing-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache update cargo
        id: cache-cargo-heavy-testing
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-heavy-testing
        with:
          path: |
            ~/.cargo/bin/
            target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: cargo heavy-testing
        run: cargo test --features heavy_testing

  cargo-audit:
    name: cargo-audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo audit
        id: cache-cargo-audit
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-audit
        with:
          path: |
            ~/.cargo/bin/
            target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: init rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - if: ${{ steps.cache-cargo-audit.outputs.cache-hit != 'true' }}
        name: install cargo audit
        run: cargo install cargo-audit

      - name: cargo audit
        run: cargo audit --deny warnings --deny unsound --deny yanked --deny unmaintained
  
  check-dep:
    name: check dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Dans un script SVP, c'est sale
      # En plus un script permet à un developpeur de le lancer en local facilement
      - name: check unused dependencies
        run: |
          failed=0
          DIRS=("simeis-data" "simeis-server")

          for dep in $(awk '
            /^\[workspace.dependencies\]/ {in_section=1; next}
            /^\[/ && in_section {exit}
            in_section && /^[a-zA-Z0-9_-]+[[:space:]]*=/ {
              match($0, /^[a-zA-Z0-9_-]+/)
              print substr($0, RSTART, RLENGTH)
            }
          ' Cargo.toml); do
            found=false
            for dir in "${DIRS[@]}"; do
              if grep -rq "$dep" "$dir"; then
                found=true
              fi
            done
            if [ "$found" = false ]; then
              echo "$dep Not used"
              failed=1
            fi
          done
          if [ "$failed" -eq 1 ]; then
            exit 1
          fi

  functional-tests:
    name: heavy-testing-functional-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache Python dependencies
        id: cache-python-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-python-deps
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ env.cache-name }}-${{ hashFiles('tests/**/*.py') }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo functional-tests
        id: cache-cargo-functional-tests
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-functional-tests
        with:
          path: target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build server with testing feature
        run: cargo build --features testing

      - name: Start server in background
        run: |
          ./target/debug/simeis-server &
          sleep 1

      - name: Run Python functional tests
        run: python -m unittest discover tests/fonctionnels/  # Bwerk, mais cohérent

  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cargo-dep cache
        id: cache-cargo-dep
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-dep
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo tarpaulin
        id: cache-cargo-tarpaulin
        uses: actions/cache@v4
        env:
          cache-name: cache-cargo-tarpaulin
        with:
          path: |
            ~/.cargo/bin/
            target/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}

      - if: ${{ steps.cache-cargo-tarpaulin.outputs.cache-hit != 'true' }}
        name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      # Propre
      - name: Run cargo tarpaulin coverage
        id: coverage
        run: |
          cargo tarpaulin --out Json -i
          coverage_percent=$(jq '.coverage' tarpaulin-report.json)
          echo "coverage=${coverage_percent}" >> $GITHUB_OUTPUT

      - name: Add label if coverage < 50%
        if: steps.coverage.outputs.coverage < 50
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: not enough tests

  verificationSource:
    name: verificationSource
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'bug/') && !startsWith(github.event.pull_request.head.ref, 'main/')}}
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "We do not accept PRs. If you have any questions, please feel free to contact us."
