name: TodoCheck

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'
      - 'master'
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check TODO/FIXME comments and validate referenced issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
      run: |
        failed=0
        
        if grep -r --exclude-dir=.github -E 'TODO|FIXME' . | grep -vE '#\s*([0-9]+|[a-zA-Z]+-[0-9]+)'; then
          failed=1
          echo "one Todo does not have a issues"
        fi
        
        for issue in $(grep -r --exclude-dir=.github -E 'TODO|FIXME' . | grep -oE '#\s*[0-9]+' | sed 's/#\s*//'); do
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$OWNER/$REPO/issues/$issue")
          
          if [ "$response" != "200" ]; then
            echo "Error: Issue #$issue does not exist"
            failed=1
          fi
        done
        
        if [ "$failed" -eq 1 ]; then
          exit 1
        fi